apiVersion: apps/v1
kind: Deployment
metadata:
  name: insecure-app
  labels:
    app: insecure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insecure
  template:
    metadata:
      labels:
        app: insecure
    spec:
      containers:
        - name: insecure-container
          image: nginx:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          # ❌ Hardcoded secret
          env:
            - name: DB_PASSWORD
              value: "supersecret123"
          # ❌ Missing resource requests/limits
          # ❌ Missing liveness/readiness probes
          # ❌ Privileged container
          securityContext:
            privileged: true
            runAsUser: 1
