name: Auto PR Generator

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    # Allow manual triggering
  push:
    branches: [ main, test-ai-review ]
    paths:
      - '**/*.yaml'
      - '**/*.yml'
      - '!**/.github/workflows/**'

jobs:
  auto-pr-generation:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install PyGithub

      - name: Run Auto PR Generator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python auto_pr_generator.py

      - name: Comment on created PRs
        if: success()
        run: |
          echo "✅ Auto PR generation completed successfully"
          echo "Check the Actions tab for created pull requests"
