name: Auto Approve Safe Fixes

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '**/*.yaml'
      - '**/*.yml'
      - '!**/.github/workflows/**'

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install PyGithub

      - name: Analyze PR for auto-approval
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python auto_approve_analyzer.py

      - name: Auto-approve if safe
        if: success() && env.AUTO_APPROVE == 'true'
        uses: hmarr/auto-approve-action@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
